# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest


steps:
- task: Docker@2
  inputs:
    containerRegistry: 'docker_hub_iy'
    repository: 'ivanyankov993/iy-app'
    command: 'buildAndPush'
    Dockerfile: '**/dockerfile'
    tags: 'latest'


- task: KubernetesManifest@1
  inputs:
    action: 'deploy'
    connectionType: 'azureResourceManager'
    azureSubscriptionConnection: 'Ivan Yankov DevOps(4f7ea576-9796-4381-8a3d-c19faee37af0)'
    azureResourceGroup: 'aks-rg'
    kubernetesCluster: 'aks-iy'
    manifests: '**/application-manifest.yaml'